name = "PRAS_HydroDispatchModifier"
uuid = "28abefa9-3fcc-42cd-9c7d-b7bc8569a628"
authors = ["Srihari Sundar", "Gord Stephen"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
